### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by AndroidKitKat** [pbui-project/pbui-main#26]
Should we add one?

**Comment by sambattalio** [comment]
https://www.gnu.org/philosophy/kind-communication.en.html

??

**Comment by sambattalio** [comment]
Reopened to allow for additional debate

**Comment by AndroidKitKat** [comment]
If you oppose a coc you're part of the problem

**Comment by sambattalio** [comment]
“A code of conduct states rules, with punishments for anyone that violates them. It is the heavy-handed way of teaching people to behave differently, and since it only comes into action when people do something against the rules, it doesn't try to teach people to do better than what the rules require. To be sure, the appointed maintainer(s) of a GNU package can, if necessary, tell a contributor to go away; but we do not want to need to have recourse to that.

The idea of the GNU Kind Communication Guidelines is to start guiding people towards kinder communication at a point well before one would even think of saying, "You are breaking the rules." The way we do this, rather than ordering people to be kind or else, is try to help people learn to make their communication more kind.”

- Richard Stallman

**Comment by AndroidKitKat** [comment]
yeah but replace gnu with pbui

**Comment by sambattalio** [comment]
I want to remind everyone to engage in kind communication through this process!

**Comment by sambattalio** [comment]
(as per CoC)

**Comment by AndroidKitKat** [comment]
As God intended

**Comment by AndroidKitKat** [comment]
@zmenciso we need your needed opinion

**Comment by sambattalio** [comment]
I am invoking Filibuster
